//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Admin
{
    public int AdminId { get; set; }
    public string Name { get; set; }
    public string Surname { get; set; }
    public Nullable<System.DateTime> Birthdate { get; set; }
    public string PhoneNumber { get; set; }
    public string City { get; set; }
    public string Email { get; set; }
    public string UserName { get; set; }
    public string Password { get; set; }
    public string Address { get; set; }
    public Nullable<int> SupportedTeamId { get; set; }
    public bool IsActive { get; set; }
    public Nullable<int> UserTypeId { get; set; }
}

public partial class Fixture
{
    public int FixtureId { get; set; }
    public int HomeTeamId { get; set; }
    public int AwayTeamId { get; set; }
    public int RefereeId { get; set; }
    public int AssistantReferee1Id { get; set; }
    public int AssistantReferee2Id { get; set; }
    public int FourthAssistantRefereeId { get; set; }
    public int HomeGoals { get; set; }
    public int AwayGoals { get; set; }
    public int Week { get; set; }
    public bool IsActive { get; set; }
}

public partial class Referee
{
    public int RefereeId { get; set; }
    public string LicenceNumber { get; set; }
    public string Name { get; set; }
    public string LastName { get; set; }
    public string City { get; set; }
    public System.DateTime BirthDate { get; set; }
    public string Email { get; set; }
    public int RefereeTypeId { get; set; }
    public bool IsActive { get; set; }
}

public partial class RefereeType
{
    public int RefereeTypeId { get; set; }
    public string RefereeType1 { get; set; }
    public bool IsActive { get; set; }
}

public partial class Supporter
{
    public int SupporterId { get; set; }
    public string Name { get; set; }
    public string SurName { get; set; }
    public Nullable<System.DateTime> Birthdate { get; set; }
    public string PhoneNumber { get; set; }
    public string City { get; set; }
    public string Email { get; set; }
    public string UserName { get; set; }
    public string Password { get; set; }
    public string Address { get; set; }
    public Nullable<int> SupportedTeamId { get; set; }
    public bool isActive { get; set; }
    public Nullable<int> UserTypeId { get; set; }
    public Nullable<bool> isApproval { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class Team
{
    public int TeamId { get; set; }
    public string TeamName { get; set; }
    public string City { get; set; }
    public string MainColor { get; set; }
    public string SecondaryColor { get; set; }
    public System.DateTime EstablishmentYear { get; set; }
    public Nullable<decimal> AccountBalance { get; set; }
    public Nullable<int> PositionLeague { get; set; }
    public Nullable<int> NumberWin { get; set; }
    public Nullable<int> NumberLose { get; set; }
    public Nullable<int> NumberEquality { get; set; }
    public bool IsActive { get; set; }
    public string TeamImage { get; set; }
    public Nullable<int> NumberMatchesPlayed { get; set; }
    public Nullable<int> NumberThrowGoal { get; set; }
    public Nullable<int> NumberGrabbedGoal { get; set; }
    public Nullable<int> GoalAverage { get; set; }
    public Nullable<int> Point { get; set; }
}

public partial class UserType
{
    public int UserTypeId { get; set; }
    public string UserType1 { get; set; }
    public Nullable<bool> isActive { get; set; }
}
